- name: HAProxy
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud" }
    - { role: role_haproxy, tags: "role_haproxy"}
    - { role: role_init_password, tags: "role_init_password"}
    - { role: role_preend, tags: "preend" }
    - { role: role_end, tags: "role_end" }
