# 本地同步公共Roles

# 服务器前置任务(ubuntu使用)
- name: haproxy
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python


# # 核心任务

- name: haproxy
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}  
    - { role: haproxy, tags: "haproxy"}
